act.flatten
MystPi/act pull request #2
Opened 2024-06-05 19:17 UTC by darky

2024-06-05 19:46 UTC, MystPi commented
What is this function generally used for? I can't think of anything off the top of my head.

2024-06-05 19:52 UTC, darky commented
`flatten` unnest nested `Action` to one level

`Result` analog - https://hexdocs.pm/gleam_stdlib/gleam/result.html#flatten
`Option` analog - https://hexdocs.pm/gleam_stdlib/gleam/option.html#flatten

In another FP programming languages sometimes it's called `chain`

2024-06-05 19:54 UTC, MystPi commented
I mean more of a practical use-case that one would typically use this function for. The function itself makes sense.

2024-06-05 20:01 UTC, darky commented
For example, you use `act.map` on some `Action` and inside this `act.map` you change `State` via `act/state.set`
On result, you receive `Action(Action)` and you want unnest it before sending it to next function in pipeline

2024-06-05 20:06 UTC, MystPi commented
Ah, that makes sense!

2024-06-05 20:10 UTC, MystPi requested changes

2024-06-05 20:10 UTC, MystPi commented on test/act_test.gleam
Let's not add tests for now since I haven't added tests for anything else yet. This module is mostly an example of how to use act.

2024-06-05 21:00 UTC, darky commented on test/act_test.gleam
fixed ✅

2024-06-06 12:05 UTC, MystPi approved these changes

2024-06-06 12:06 UTC, merged